[package]
name = "aiwebscraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version ="0.12.9", features = ["blocking","json"]}
rust-bert = "0.23.0"
select = "0.6.0"
serde = { version = "1.0.214", features =["derive"]}
